services:
  tts:
    build: ./
    image: knowbud/edge-tts-service:latest
    container_name: local-edge-tts
    ports:
      - "5501:5501"
    environment:
      # 🌟 最优儿童真人音色（晓晓 = 温柔女童）
      - EDGE_TTS_VOICE=zh-CN-XiaoxiaoNeural
    restart: unless-stopped

  asr:
    image: onerahmet/openai-whisper-asr-webservice:latest
    container_name: local-whisper-asr
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=base
    restart: unless-stopped